/**
 * Compare Oracle vs Adaptive AI Performance
 * 
 * Compares products generated by Oracle vs Adaptive AI to help with migration decision.
 */

import 'dotenv/config';
import { getFirestore } from 'firebase-admin/firestore';

interface ProductStats {
  source: string;
  count: number;
  avgPrice: number;
  totalRevenue: number;
  avgDescriptionLength: number;
  niches: Record<string, number>;
  productTypes: Record<string, number>;
  createdAtRange: { earliest: Date | null; latest: Date | null };
}

async function main() {
  console.log('🔍 Comparing Oracle vs Adaptive AI Performance...\n');

  try {
    const db = getFirestore();
    
    // Fetch all products
    const productsSnapshot = await db.collection('products').get();
    const products = productsSnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data(),
    }));

    console.log(`📦 Total products: ${products.length}\n`);

    // Separate by source
    const oracleProducts = products.filter(p => p.source === 'oracle');
    const adaptiveProducts = products.filter(p => p.source === 'adaptive_ai');
    const otherProducts = products.filter(p => p.source !== 'oracle' && p.source !== 'adaptive_ai');

    // Calculate stats for each source
    const oracleStats = calculateStats(oracleProducts, 'oracle');
    const adaptiveStats = calculateStats(adaptiveProducts, 'adaptive_ai');

    // Display comparison
    console.log('='.repeat(60));
    console.log('📊 ORACLE STATS');
    console.log('='.repeat(60));
    displayStats(oracleStats);

    console.log('\n' + '='.repeat(60));
    console.log('📊 ADAPTIVE AI STATS');
    console.log('='.repeat(60));
    displayStats(adaptiveStats);

    // Comparison summary
    console.log('\n' + '='.repeat(60));
    console.log('📈 COMPARISON SUMMARY');
    console.log('='.repeat(60));
    
    if (oracleStats.count > 0 && adaptiveStats.count > 0) {
      const priceDiff = ((adaptiveStats.avgPrice - oracleStats.avgPrice) / oracleStats.avgPrice * 100).toFixed(1);
      const descDiff = ((adaptiveStats.avgDescriptionLength - oracleStats.avgDescriptionLength) / oracleStats.avgDescriptionLength * 100).toFixed(1);
      
      console.log(`Products Generated:`);
      console.log(`  Oracle: ${oracleStats.count}`);
      console.log(`  Adaptive AI: ${adaptiveStats.count}`);
      console.log(`  Ratio: ${(adaptiveStats.count / oracleStats.count * 100).toFixed(1)}%`);
      
      console.log(`\nAverage Price:`);
      console.log(`  Oracle: $${oracleStats.avgPrice.toFixed(2)}`);
      console.log(`  Adaptive AI: $${adaptiveStats.avgPrice.toFixed(2)}`);
      console.log(`  Difference: ${priceDiff}%`);
      
      console.log(`\nDescription Quality:`);
      console.log(`  Oracle: ${oracleStats.avgDescriptionLength.toFixed(0)} chars`);
      console.log(`  Adaptive AI: ${adaptiveStats.avgDescriptionLength.toFixed(0)} chars`);
      console.log(`  Difference: ${descDiff}%`);
      
      console.log(`\nRevenue:`);
      console.log(`  Oracle: $${oracleStats.totalRevenue.toFixed(2)}`);
      console.log(`  Adaptive AI: $${adaptiveStats.totalRevenue.toFixed(2)}`);
    } else if (oracleStats.count > 0) {
      console.log('⚠️  Only Oracle products found. Adaptive AI has not generated products yet.');
      console.log('   Run: npm run adaptive-ai:generate 3');
    } else if (adaptiveStats.count > 0) {
      console.log('✅ Only Adaptive AI products found. Migration appears complete!');
    } else {
      console.log('⚠️  No Oracle or Adaptive AI products found.');
    }

    if (otherProducts.length > 0) {
      console.log(`\n📋 Other products (not Oracle/Adaptive AI): ${otherProducts.length}`);
    }

    // Recommendations
    console.log('\n' + '='.repeat(60));
    console.log('💡 RECOMMENDATIONS');
    console.log('='.repeat(60));
    
    if (adaptiveStats.count === 0) {
      console.log('1. Generate Adaptive AI products: npm run adaptive-ai:generate 3');
      console.log('2. Wait for sales data to accumulate');
      console.log('3. Compare performance after 1-2 weeks');
    } else if (oracleStats.count > adaptiveStats.count * 2) {
      console.log('1. Oracle still generating more products');
      console.log('2. Consider stopping Oracle once Adaptive AI proves stable');
      console.log('3. Monitor Adaptive AI performance for 1-2 weeks');
    } else if (adaptiveStats.count >= oracleStats.count) {
      console.log('1. ✅ Adaptive AI is generating products successfully');
      console.log('2. ✅ Safe to stop Oracle');
      console.log('3. Monitor Adaptive AI for continued performance');
    }

    process.exit(0);
  } catch (error: any) {
    console.error('❌ Error comparing products:', error.message);
    process.exit(1);
  }
}

function calculateStats(products: any[], source: string): ProductStats {
  const stats: ProductStats = {
    source,
    count: products.length,
    avgPrice: 0,
    totalRevenue: 0,
    avgDescriptionLength: 0,
    niches: {},
    productTypes: {},
    createdAtRange: { earliest: null, latest: null },
  };

  if (products.length === 0) {
    return stats;
  }

  let totalPrice = 0;
  let totalDescLength = 0;
  let earliestDate: Date | null = null;
  let latestDate: Date | null = null;

  for (const product of products) {
    // Price
    const price = product.price_usd || product.price || 0;
    totalPrice += price;
    stats.totalRevenue += price; // Simplified - would need sales data for real revenue

    // Description length
    const desc = product.description || product.body_html || '';
    const descText = typeof desc === 'string' ? desc.replace(/<[^>]*>/g, '') : '';
    totalDescLength += descText.length;

    // Niches
    const niche = product.niche || 'unknown';
    stats.niches[niche] = (stats.niches[niche] || 0) + 1;

    // Product types
    const type = product.product_type || product.productType || 'unknown';
    stats.productTypes[type] = (stats.productTypes[type] || 0) + 1;

    // Date range
    const createdAt = product.createdAt?.toDate?.() || 
                     (product.createdAt ? new Date(product.createdAt) : null);
    if (createdAt) {
      if (!earliestDate || createdAt < earliestDate) {
        earliestDate = createdAt;
      }
      if (!latestDate || createdAt > latestDate) {
        latestDate = createdAt;
      }
    }
  }

  stats.avgPrice = totalPrice / products.length;
  stats.avgDescriptionLength = totalDescLength / products.length;
  stats.createdAtRange.earliest = earliestDate;
  stats.createdAtRange.latest = latestDate;

  return stats;
}

function displayStats(stats: ProductStats): void {
  if (stats.count === 0) {
    console.log('No products found');
    return;
  }

  console.log(`Total Products: ${stats.count}`);
  console.log(`Average Price: $${stats.avgPrice.toFixed(2)}`);
  console.log(`Total Revenue: $${stats.totalRevenue.toFixed(2)}`);
  console.log(`Avg Description Length: ${stats.avgDescriptionLength.toFixed(0)} chars`);
  
  if (stats.createdAtRange.earliest && stats.createdAtRange.latest) {
    console.log(`Date Range: ${stats.createdAtRange.earliest.toISOString().split('T')[0]} to ${stats.createdAtRange.latest.toISOString().split('T')[0]}`);
  }

  console.log(`\nNiches:`);
  Object.entries(stats.niches)
    .sort((a, b) => b[1] - a[1])
    .forEach(([niche, count]) => {
      console.log(`  ${niche}: ${count}`);
    });

  console.log(`\nProduct Types:`);
  Object.entries(stats.productTypes)
    .sort((a, b) => b[1] - a[1])
    .forEach(([type, count]) => {
      console.log(`  ${type}: ${count}`);
    });
}

main();

